# Generated by Django 4.2.16 on 2025-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='member.member'),
        ),
    ]
