# Generated by Django 4.2.23 on 2025-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
